pdf:
	rm Rep-Res-Book.Rmd & Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::pdf_book')"

epub:
	rm Rep-Res-Book.Rmd & Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::epub_book')"

html:
	rm Rep-Res-Book.Rmd & Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
